
CREATE TABLE staff (
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(100),
    EMP_SALARY NUMBER(10,2),
    DEPT_ID NUMBER
);


INSERT INTO STAFF VALUES (101, 'Rahul', 50000, 10);
INSERT INTO STAFF VALUES (102, 'Amit', 60000, 10);
INSERT INTO STAFF VALUES (103, 'Priya', 450000, 20);
INSERT INTO STAFF VALUES (104, 'RONY', 55000, 10);
INSERT INTO STAFF VALUES (105, 'ANIL', 66000, 10);
INSERT INTO STAFF VALUES (106, 'Pri', 46000, 20);
INSERT INTO STAFF VALUES (107, 'Rah', 52000, 10);
INSERT INTO STAFF VALUES (108, 'Ammy', 60000, 10);


DECLARE
CURSOR STAFF_CURSOR IS SELECT EMP_NAME,EMP_SALARY FROM STAFF 
ORDER BY EMP_SALARY DESC
FETCH FIRST 5 ROWS ONLY;
V_EMP_NAME STAFF.EMP_NAME%TYPE;
V_EMP_SALARY STAFF.EMP_SALARY%TYPE;
BEGIN 
    OPEN STAFF_CURSOR;
    FETCH STAFF_CURSOR INTO V_EMP_NAME,V_EMP_SALARY;
    WHILE STAFF_CURSOR%FOUND
    LOOP
        DBMS_OUTPUT.PUT_LINE (V_EMP_NAME||V_EMP_SALARY);
        FETCH STAFF_CURSOR INTO V_EMP_NAME,V_EMP_SALARY;
        END LOOP;
        CLOSE STAFF_CURSOR;
END;
   
    
