
CREATE TABLE EMPLOYEES(EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(100)NOT NULL, SALARY NUMERIC(10,2),
DEPARTMENT_NAME VARCHAR(100));
CREATE OR REPLACE PROCEDURE Insert_Employee(P_EMP_ID INT,
P_EMP_NAME VARCHAR,P_SALARY NUMERIC(10,2),P_DEPARTMENT_NAME VARCHAR)
LANGUAGE plpgsql
AS $$
BEGIN
  IF P_EMP_ID%2=0 THEN
    RAISE EXCEPTION'EVEN EMP_ID IS NOT ALLOWED';
  ELSE 
    INSERT INTO EMPLOYEES(EMP_ID,EMP_NAME,SALARY,DEPARTMENT_NAME)
    VALUES(P_EMP_ID,P_EMP_NAME,P_SALARY,P_DEPARTMENT_NAME);
    RAISE NOTICE 'EMPLOYEES  WITH ID % INSERTES SUCCESSFULLY',P_EMP_ID;
  END IF;
END;
$$;
CALL Insert_Employee(1,'Ankita',120000,'CSE');
SELECT *FROM EMPLOYEES;
